language: ruby
rvm:
- 2.0.0

before_install:
- echo before_install
- ./success.sh

install:
- echo install
- ./success.sh

before_script:
- echo before_script
- ./success.sh

script:
- echo script
- ./success.sh

before_cache:
- echo cache
- ./success.sh

after_success:
- echo after_success
- ./success.sh

after_failure:
- echo after_failure
- ./success.sh

before_deploy:
- echo before_deploy
- ./success.sh

# deploy:
# - echo deploy
# - ./success.sh

after_deploy:
- echo after_deploy
- ./success.sh

after_script:
- echo after_script
- ./success.sh
